#!/usr/bin/env bash

set -eox pipefail

#############
## Globals ##
#############
kubectl=$(which kubectl)

###############
## Functions ##
###############

# Args: None
function print_usage {
    echo "Usage: $0 --source_context=[context_name] --source_deployment=[deployment_name] --source_port=[port_number] --target_context=[name] --target_deployment|--target_pod=[deployment_name|pod_name] --target_port=[port_number]"
    exit 1
}

# Args:
#  $1: kubectl context
#  $2: deployment name
function get_k8s_replicaset_name_from_deployment_name {
    local kubectl_context=$1
    local deployment_name=$2
    local replicaset_name=$(
      ${kubectl} --context=${kubectl_context} get replicasets -o json | \
          jq \
              --raw-output \
                  ".items \
                      | map(select(.metadata.ownerReferences[0].kind == \"Deployment\" and \
                          .metadata.ownerReferences[0].name == \"${deployment_name}\" and \
                          .status.replicas > 0)) \
                      | map(.metadata.name)[0] \
                  "
    )
    echo ${replicaset_name}
}

# Args:
#  $1: kubectl context
#  $2: replicaset name
function get_k8s_pod_name_from_replicaset_name {
    local kubectl_context=$1
    local replicaset_name=$2
    local pod_name=$(
        ${kubectl} --context=${kubectl_context} get pods -o json | \
            jq \
                --raw-output \
                    ".items \
                        | map(select(.metadata.ownerReferences[0].kind == \"ReplicaSet\" and \
                              .metadata.ownerReferences[0].name == \"${replicaset_name}\")) \
                        | map(.metadata.name)[0] \
                    "
    )
    echo ${pod_name}
}

# Args:
#  $1: kubectl context
#  $2: deployment name
function get_k8s_pod_name_from_deployment_name {
    local kubectl_context=$1
    local deployment_name=$2
    local replicaset_name=$(get_k8s_replicaset_name_from_deployment_name ${kubectl_context} ${deployment_name})
    local pod_name=$(get_k8s_pod_name_from_replicaset_name ${kubectl_context} ${replicaset_name})
    echo ${pod_name}
}

#####################
## Parse Arguments ##
#####################

# Source settings
source_context=
source_deployment=
source_port=

# Target settings
target_context=
target_deployment=
target_pod=
target_port=

while [[ $# -gt 0 ]]
do
key="$1"
case $key in

    --source_context=*)
    source_context="${key#*=}"
    shift # past argument=value
    ;;

    --source_deployment=*)
    source_deployment="${key#*=}"
    shift # past argument=value
    ;;

    --source_port=*)
    source_port="${key#*=}"
    shift # past argument=value
    ;;

    --target_context=*)
    target_context="${key#*=}"
    shift # past argument=value
    ;;

    --target_deployment=*)
    target_deployment="${key#*=}"
    shift # past argument=value
    ;;

    --target_pod=*)
    target_pod="${key#*=}"
    shift # past argument=value
    ;;

    --target_port=*)
    target_port="${key#*=}"
    shift # past argument=value
    ;;

    *)    # unknown option
      echo "Unknown option ${key}"
      print_usage
    ;;

esac
done

# Ensure that all mandatory arguments were specified

if [[ -z "${source_context}" ]] \
    || [[ -z "${source_deployment}" ]] \
    || [[ -z "${source_port}" ]] \
    || [[ -z "${target_context}" ]] \
    || [[ -z "${target_port}" ]]; then
    print_usage
fi

# Only one of target_deployment and target_pod is required
if [[ -z "${target_deployment}" ]] && [[ -z "${target_pod}" ]]; then
    print_usage
elif [[ -z "${target_pod}" ]]; then
    target_pod=$(get_k8s_pod_name_from_deployment_name ${target_context} ${target_deployment})
fi


####################################
## Prepare Telepresence arguments ##
####################################

osx_gcloud_path=${HOME}/Applications/gcloud/google-cloud-sdk/bin/gcloud
docker_cmd="\
    # Make tele-proxy works on OSX.
    mkdir -p \$(dirname $osx_gcloud_path); \
    ln -s /usr/bin/gcloud $osx_gcloud_path; \
    while true; do kubectl --context ${target_context} port-forward ${target_pod} ${source_port}:${target_port} || echo 'retrying... ' && sleep 2; done\
"

# Mount:
# - kubectl config
# - aws CLI config
# - gcloud CLI config
docker_options=( )
docker_options+=("-v" "${HOME}/.aws:/root/.aws" )
docker_options+=("-v" "${HOME}/.kube/config:/root/.kube/config" )
docker_options+=("-v" "${HOME}/.config/gcloud:/root/.config/gcloud" )
docker_options+=("-e" "AWS_ACCESS_KEY_ID" )
docker_options+=("-e" "AWS_SECRET_ACCESS_KEY" )

docker_image=flared/teleproxy:latest

# TODO(aviau): Support statefulset too. See the --deployment-type flag of github.com/flared/telepresence
telepresence_options=( )
telepresence_options+=( "--swap-deployment" "${source_deployment}" )

######################
## Run Telepresence ##
######################

telepresence \
    --context ${source_context} \
    ${telepresence_options[@]} \
    --docker-run \
        --rm -it \
        ${docker_options[@]} \
        ${docker_image} \
        bash -c "${docker_cmd}";
